language: ruby
dist: trusty
cache: bundler
sudo: required
env:
  - TEST_GROUP="./script/check_syntax"
  - TEST_GROUP="rake parallel:spec"
  - TEST_GROUP="rake parallel:features[^features/admins]                -f Ao3Cucumber::Formatter --color""
  - TEST_GROUP="rake parallel:features[^features/bookmarks]             -f Ao3Cucumber::Formatter --color""
  - TEST_GROUP="rake parallel:features[^features/collections]           -f Ao3Cucumber::Formatter --color""
  - TEST_GROUP="rake parallel:features[^features/comments_and_kudos]    -f Ao3Cucumber::Formatter --color""
  - TEST_GROUP="rake parallel:features[^features/gift_exchanges]        -f Ao3Cucumber::Formatter --color""
  - TEST_GROUP="rake parallel:features[^features/importing]             -f Ao3Cucumber::Formatter --color""
  - TEST_GROUP="rake parallel:features[^features/other_a]               -f Ao3Cucumber::Formatter --color""
  - TEST_GROUP="rake parallel:features[^features/other_b]               -f Ao3Cucumber::Formatter --color""
  - TEST_GROUP="rake parallel:features[^features/prompt_memes_a]        -f Ao3Cucumber::Formatter --color""
  - TEST_GROUP="rake parallel:features[^features/prompt_memes_b]        -f Ao3Cucumber::Formatter --color""
  - TEST_GROUP="rake parallel:features[^features/prompt_memes_c]"
  - TEST_GROUP="rake parallel:features[^features/tag_sets]"
  - TEST_GROUP="rake parallel:features[^features/tags_and_wrangling]"
  - TEST_GROUP="rake parallel:features[^features/users]"
  - TEST_GROUP="rake parallel:features[^features/works]"
rvm:
  - "2.2.5"
services:
  - elasticsearch
  - redis-server
  - memcached
script:
  - export COVERALLS_PARALLEL=true
  - RAILS_ENV=test bundle exec rake parallel:create --trace
  - RAILS_ENV=test bundle exec rake parallel:load_schema --trace
  - RAILS_ENV=test bundle exec rake parallel:migrate --trace
  - travis_retry bundle exec $TEST_GROUP
before_script:
  - bash script/travis_configure.sh
  - bash script/travis_elasticsearch_upgrade.sh
  - bash script/travis_multiple_redis.sh
notifications:
  email:
    recipients:
      - otw-coders-extra@transformativeworks.org
    on_success: change
    on_failure: always
  irc:
    channels:
      - "irc.freenode.org#otw-dev"
    on_success: change
    on_failure: change
  webhooks: https://coveralls.io/webhook?repo_token=COVERALLS_REPO_TOKEN
